export const SERVICES = [
  "Air Duct Cleaning",
  "Carpet Cleaning",
  "Chimney Cleaning",
  "Cleaning",
  "Deep Cleaning",
  "House Cleaning",
  "Move-In/Move-Out Cleaning",
  "Oven Cleaning",
  "Post-Construction Cleaning",
  "Refrigerator Cleaning",
  "Spring Cleaning",
  "Tile and Grout Cleaning",
  "Upholstery Cleaning",
  "Window Cleaning",
  "Aquarium Maintenance",
  "Dog Walking",
  "Pet Cleanup",
  "Pet Grooming",
  "Pet Kennel Cleaning",
  "Pet Sitting",
  "Pet Training",
  "Pet Waste Removal",
  "Appliance Repair",
  "Appliance Installation",
  "Range Hood Installation",
  "Basement Waterproofing",
  "Bathtub Refinishing",
  "Ceiling Repair",
  "Drywall Repair",
  "Foundation Repair",
  "Garage Door Repair",
  "Glass Repair",
  "Grout Repair",
  "Gutter Repair",
  "Gutter Installation & Cleaning",
  "Home Maintenance",
  "Masonry Repair",
  "Minor Home Repairs",
  "Siding Repair",
  "Sump Pump Maintenance",
  "Water Heater Maintenance",
  "Windows & Doors Repair",
  "Air Purifier Installation",
  "Cabinet Installation",
  "Cabinet Refacing",
  "Countertop Installation",
  "Countertop Repair",
  "Backsplash Installation",
  "Crown Molding Installation",
  "Curtain Rod Installation",
  "EV Charger Installation",
  "Floor Installation",
  "Floor Refinishing",
  "Humidifier Installation",
  "Install Blinds",
  "Install Window Treatments",
  "Light Installation",
  "Lock Installation or Repair",
  "Mirror Installation",
  "Pet Door Installation",
  "Safe Installation",
  "Satellite & Set Top Boxes Installation",
  "Security System Installation",
  "Security Camera Installation",
  "Doorbell Camera Installation",
  "Shelf Installation",
  "Shelving Installation",
  "Skylight Installation",
  "Smart Home Installation",
  "Smart Lighting Setup",
  "Smart Lock Installation",
  "Smart Thermostat Installation",
  "Sprinkler System Installation",
  "Sprinkler System Maintenance",
  "Thermostat Installation & Repair",
  "TV & Home Theater Installation",
  "TV Mounting",
  "Deck Construction",
  "Driveway Sealing",
  "Fencing",
  "Gate Installation & Repair",
  "Garden Bed Installation",
  "Gardening",
  "Landscaping",
  "Lawncare",
  "Outdoor Kitchen Installation",
  "Outdoor Lighting Installation",
  "Patio Installation",
  "Pergola Construction",
  "Pond Maintenance",
  "Pressure Washing",
  "Retaining Wall Construction",
  "Retaining Wall Installation",
  "Shed Installation",
  "Snow Removal",
  "Stump Grinding",
  "Tree Removal",
  "Yard Work",
  "Artificial Turf Installation",
  "Drainage Solutions",
  "French Drain Installation",
  "Carbon Monoxide Detector Maintenance",
  "Fireproofing",
  "Smoke Detector Maintenance",
  "Energy Audit",
  "Weatherproofing",
  "Weatherstripping",
  "Window Sealing",
  "Insulation Installation",
  "Green Roof Installation",
  "Solar Panel Installation",
  "Solar Panel Maintenance",
  "Generator Installation",
  "Generator Maintenance",
  "Backup Power System Installation",
  "Rainwater Harvesting System Installation",
  "Composting System Setup",
  "Asbestos Removal",
  "Mold Remediation",
  "Pest Control",
  "Rodent Control",
  "Wildlife Removal",
  "Baby Proofing",
  "Nursery Setup",
  "Playground Installation",
  "Toy Organization",
  "Wheelchair Ramp Installation",
  "Grab Bar Installation",
  "Accessibility Modifications",
  "Stair Lift Installation",
  "Holiday Decoration Removal",
  "Holiday Decoration Setup",
  "Party Cleanup",
  "Party Setup",
  "Winterization Services",
  "Storm Damage Repair",
  "Emergency Board-Up Services",
  "Acoustic Panel Installation",
  "Bed Assembly",
  "Builders",
  "Carpentry Services",
  "Ceiling Fan Repair",
  "Decoration",
  "Fence Painting",
  "Furniture Assembly",
  "Hang Art",
  "Hang Curtains",
  "Home Improvement",
  "Home Staging",
  "Home Theater Setup",
  "IKEA Assembly",
  "Indoor Painting",
  "Interior Decoration",
  "Light Carpentry",
  "Odor Removal",
  "Organization",
  "Painting & Decorating",
  "Picture Hanging",
  "Room Measurement",
  "Soundproofing",
  "Vintage Home Restoration",
  "Wallpapering",
  "Wallpaper Removal",
  "Asphalt Shingle Preservation",
  "Asphalt Shingle Rejuvenation",
  "Asphalt Shingles Maintenance",
  "Asphalt Shingles Replacement",
  "Cedar Shake Maintenance",
  "Cedar Shake Replacement",
  "Roof Maintenance",
  "Roof Repair & Replacement",
  "Attic Cleaning",
  "Car Washing",
  "Elevator Maintenance",
  "Fireplace Maintenance",
  "Home Automation Services",
  "Home Gym Setup",
  "Home Network Setup",
  "Home Office Setup",
  "Computer Setup & Troubleshooting",
  "Printer Setup & Installation",
  "Laundry and Ironing",
  "Linens Washing",
  "Packing & Unpacking",
  "Pool Maintenance",
  "Pool Table Maintenance",
  "Sauna Maintenance",
  "Sewing",
  "Structural Maintenance",
  "Trash & Furniture Removal",
  "Wine Cellar Maintenance",
  "Blinds Repair",
  "Dry Cleaning",
  "Electrical Assistance",
  "General Handyman",
  "Heavy Lifting & Loading",
  "Help Moving",
  "HVAC Maintenance",
  "Outdoor Maintenance",
  "Plumbing",
  "Septic Tank Maintenance",
  "Tile Installation",
  "Dog Run Installation",
].sort()

// Services that require structure details (house size, stories, property type)
export const SERVICES_REQUIRING_STRUCTURE_DETAILS = [
  "Accessibility Modifications",
  "Asphalt Shingles Maintenance",
  "Asphalt Shingles Replacement",
  "Basement Waterproofing",
  "Builders",
  "Cabinet Installation",
  "Carpentry Services",
  "Cedar Shake Maintenance",
  "Cedar Shake Replacement",
  "Ceiling Repair",
  "Countertop Installation",
  "Deck Construction",
  "Drywall Repair",
  "Floor Installation",
  "Floor Refinishing",
  "Foundation Repair",
  "Green Roof Installation",
  "Gutter Installation & Cleaning",
  "Gutter Repair",
  "Home Improvement",
  "Home Maintenance",
  "Indoor Painting",
  "Insulation Installation",
  "Light Carpentry",
  "Masonry Repair",
  "Minor Home Repairs",
  "Painting & Decorating",
  "Patio Installation",
  "Pergola Construction",
  "Roof Maintenance",
  "Roof Repair & Replacement",
  "Siding Repair",
  "Skylight Installation",
  "Solar Panel Installation",
  "Structural Maintenance",
  "Wallpapering",
  "Window Sealing",
]

export const SERVICE_RELATIONSHIPS: Record<string, string[]> = {
  // Electrical & Smart Home
  "Electrical Assistance": [
    "EV Charger Installation",
    "Smart Home Installation",
    "Light Installation",
    "Smart Lighting Setup",
    "Smart Thermostat Installation",
  ],
  "EV Charger Installation": [
    "Electrical Assistance",
    "Solar Panel Installation",
    "Energy Audit",
    "Generator Installation",
  ],
  "Smart Home Installation": [
    "Home Automation Services",
    "Smart Lighting Setup",
    "Smart Lock Installation",
    "Security System Installation",
    "Smart Thermostat Installation",
  ],
  "Smart Lighting Setup": ["Smart Home Installation", "Light Installation", "Electrical Assistance"],
  "Smart Thermostat Installation": ["HVAC Maintenance", "Smart Home Installation", "Energy Audit"],
  "Security System Installation": [
    "Smart Home Installation",
    "Smart Lock Installation",
    "Smoke Detector Maintenance",
    "Security Camera Installation",
    "Doorbell Camera Installation",
  ],
  "Security Camera Installation": [
    "Security System Installation",
    "Doorbell Camera Installation",
    "Smart Home Installation",
  ],
  "Doorbell Camera Installation": [
    "Security System Installation",
    "Security Camera Installation",
    "Smart Lock Installation",
  ],

  // Plumbing & Water
  Plumbing: [
    "Water Heater Maintenance",
    "Sump Pump Maintenance",
    "Septic Tank Maintenance",
    "Bathtub Refinishing",
    "Drainage Solutions",
  ],
  "Water Heater Maintenance": ["Plumbing", "HVAC Maintenance", "Energy Audit"],
  "Septic Tank Maintenance": ["Plumbing", "Drainage Solutions"],
  "Drainage Solutions": ["French Drain Installation", "Plumbing", "Basement Waterproofing"],
  "French Drain Installation": ["Drainage Solutions", "Landscaping", "Retaining Wall Installation"],

  // HVAC & Climate
  "HVAC Maintenance": [
    "Air Duct Cleaning",
    "Air Purifier Installation",
    "Thermostat Installation & Repair",
    "Energy Audit",
    "Smart Thermostat Installation",
  ],
  "Air Duct Cleaning": ["HVAC Maintenance", "Air Purifier Installation"],
  "Air Purifier Installation": ["HVAC Maintenance", "Air Duct Cleaning"],
  "Humidifier Installation": ["HVAC Maintenance", "Air Purifier Installation"],

  // Roofing
  "Roof Repair & Replacement": [
    "Roof Maintenance",
    "Asphalt Shingles Replacement",
    "Cedar Shake Replacement",
    "Gutter Repair",
    "Skylight Installation",
  ],
  "Roof Maintenance": [
    "Roof Repair & Replacement",
    "Gutter Installation & Cleaning",
    "Chimney Cleaning",
    "Asphalt Shingles Maintenance",
  ],
  "Asphalt Shingles Replacement": ["Roof Repair & Replacement", "Asphalt Shingles Maintenance", "Roof Maintenance"],
  "Asphalt Shingles Maintenance": ["Asphalt Shingle Preservation", "Asphalt Shingle Rejuvenation", "Roof Maintenance"],
  "Cedar Shake Replacement": ["Cedar Shake Maintenance", "Roof Repair & Replacement"],

  // Landscaping & Outdoor
  Landscaping: [
    "Lawncare",
    "Gardening",
    "Garden Bed Installation",
    "Tree Removal",
    "Yard Work",
    "Outdoor Lighting Installation",
  ],
  Lawncare: ["Landscaping", "Yard Work", "Gardening", "Sprinkler System Maintenance"],
  Gardening: ["Landscaping", "Lawncare", "Garden Bed Installation", "Composting System Setup"],
  "Tree Removal": ["Stump Grinding", "Landscaping", "Yard Work"],
  "Yard Work": ["Landscaping", "Lawncare", "Outdoor Maintenance", "Snow Removal"],
  "Outdoor Maintenance": ["Yard Work", "Pressure Washing", "Gutter Installation & Cleaning", "Snow Removal"],
  "Sprinkler System Installation": ["Sprinkler System Maintenance", "Landscaping", "Drainage Solutions"],
  "Sprinkler System Maintenance": ["Sprinkler System Installation", "Lawncare"],
  "Artificial Turf Installation": ["Landscaping", "Yard Work", "Drainage Solutions"],
  "Outdoor Lighting Installation": ["Landscaping", "Deck Construction", "Patio Installation", "Electrical Assistance"],

  // Painting & Walls
  "Painting & Decorating": ["Indoor Painting", "Wallpapering", "Drywall Repair", "Ceiling Repair", "Fence Painting"],
  "Indoor Painting": ["Painting & Decorating", "Wallpapering", "Drywall Repair"],
  "Drywall Repair": ["Indoor Painting", "Ceiling Repair", "Painting & Decorating"],
  Wallpapering: ["Painting & Decorating", "Wallpaper Removal", "Indoor Painting"],
  "Fence Painting": ["Fencing", "Painting & Decorating", "Deck Construction"],

  // Cleaning
  Cleaning: ["House Cleaning", "Deep Cleaning", "Carpet Cleaning", "Window Cleaning"],
  "House Cleaning": ["Cleaning", "Deep Cleaning", "Move-In/Move-Out Cleaning", "Post-Construction Cleaning"],
  "Deep Cleaning": ["Cleaning", "House Cleaning", "Spring Cleaning", "Carpet Cleaning"],
  "Carpet Cleaning": ["Cleaning", "Upholstery Cleaning", "Deep Cleaning", "Tile and Grout Cleaning"],
  "Window Cleaning": ["Pressure Washing", "Gutter Installation & Cleaning", "Cleaning"],
  "Post-Construction Cleaning": ["House Cleaning", "Deep Cleaning", "Trash & Furniture Removal"],
  "Spring Cleaning": ["Deep Cleaning", "House Cleaning", "Attic Cleaning"],

  // Solar & Energy
  "Solar Panel Installation": [
    "Solar Panel Maintenance",
    "EV Charger Installation",
    "Energy Audit",
    "Green Roof Installation",
  ],
  "Solar Panel Maintenance": ["Solar Panel Installation", "Energy Audit"],
  "Energy Audit": [
    "Insulation Installation",
    "Solar Panel Installation",
    "HVAC Maintenance",
    "Weatherstripping",
    "Weatherproofing",
  ],
  "Generator Installation": ["Generator Maintenance", "Backup Power System Installation", "Electrical Assistance"],
  "Generator Maintenance": ["Generator Installation", "Backup Power System Installation"],

  // Pet Services
  "Pet Sitting": ["Pet Grooming", "Dog Walking", "Pet Training", "Pet Waste Removal"],
  "Dog Walking": ["Pet Sitting", "Pet Waste Removal", "Pet Training", "Dog Run Installation"],
  "Pet Grooming": ["Pet Sitting", "Pet Cleanup", "Pet Kennel Cleaning"],
  "Dog Run Installation": ["Fencing", "Dog Walking", "Pet Sitting"],

  // Gutters
  "Gutter Installation & Cleaning": ["Gutter Repair", "Roof Maintenance", "Pressure Washing"],
  "Gutter Repair": ["Gutter Installation & Cleaning", "Roof Repair & Replacement"],

  // Outdoor Structures
  "Deck Construction": [
    "Fence Painting",
    "Fencing",
    "Patio Installation",
    "Outdoor Lighting Installation",
    "Pergola Construction",
  ],
  "Patio Installation": [
    "Deck Construction",
    "Outdoor Kitchen Installation",
    "Pergola Construction",
    "Retaining Wall Construction",
  ],
  "Pergola Construction": ["Deck Construction", "Patio Installation", "Outdoor Lighting Installation"],
  Fencing: ["Gate Installation & Repair", "Fence Painting", "Deck Construction"],
  "Retaining Wall Construction": ["Retaining Wall Installation", "Landscaping", "Drainage Solutions"],

  // Winter & Weather
  "Snow Removal": ["Driveway Sealing", "Pressure Washing", "Outdoor Maintenance", "Winterization Services"],
  "Winterization Services": ["Snow Removal", "Weatherproofing", "Storm Damage Repair"],
  "Storm Damage Repair": ["Winterization Services", "Emergency Board-Up Services", "Roof Repair & Replacement"],

  // Assembly & Installation
  "Furniture Assembly": ["IKEA Assembly", "Bed Assembly", "Shelf Installation"],
  "IKEA Assembly": ["Furniture Assembly", "Bed Assembly"],
  "Shelving Installation": ["Shelf Installation", "Organization", "Cabinet Installation"],

  // Entertainment & Tech
  "TV Mounting": ["TV & Home Theater Installation", "Home Theater Setup", "Mirror Installation"],
  "Home Theater Setup": [
    "TV Mounting",
    "TV & Home Theater Installation",
    "Smart Home Installation",
    "Acoustic Panel Installation",
  ],
  "Home Network Setup": ["Computer Setup & Troubleshooting", "Smart Home Installation", "Home Office Setup"],
  "Computer Setup & Troubleshooting": ["Home Network Setup", "Printer Setup & Installation", "Home Office Setup"],
  "Printer Setup & Installation": ["Computer Setup & Troubleshooting", "Home Office Setup"],

  // Floors & Surfaces
  "Floor Installation": ["Floor Refinishing", "Tile Installation", "Carpentry Services"],
  "Tile Installation": ["Floor Installation", "Backsplash Installation", "Tile and Grout Cleaning"],
  "Countertop Installation": ["Countertop Repair", "Cabinet Installation", "Backsplash Installation"],
  "Backsplash Installation": ["Tile Installation", "Countertop Installation", "Kitchen work"],

  // Cabinets & Storage
  "Cabinet Installation": ["Countertop Installation", "Light Carpentry", "Shelf Installation", "Cabinet Refacing"],
  "Cabinet Refacing": ["Cabinet Installation", "Countertop Installation"],

  // Pool & Water Features
  "Pool Maintenance": ["Pond Maintenance", "Pressure Washing"],
  "Pond Maintenance": ["Pool Maintenance", "Landscaping"],

  // Safety & Hazards
  "Pest Control": ["Rodent Control", "Wildlife Removal", "Mold Remediation"],
  "Mold Remediation": ["Pest Control", "Asbestos Removal", "Basement Waterproofing"],
  "Asbestos Removal": ["Mold Remediation", "Attic Cleaning"],
  "Smoke Detector Maintenance": [
    "Carbon Monoxide Detector Maintenance",
    "Security System Installation",
    "Fireproofing",
  ],

  // Appliances
  "Appliance Repair": ["Appliance Installation", "Refrigerator Cleaning", "Oven Cleaning", "Range Hood Installation"],
  "Appliance Installation": ["Appliance Repair", "Range Hood Installation"],

  // Accessibility
  "Accessibility Modifications": ["Wheelchair Ramp Installation", "Grab Bar Installation", "Stair Lift Installation"],
  "Wheelchair Ramp Installation": ["Accessibility Modifications", "Deck Construction"],
  "Grab Bar Installation": ["Accessibility Modifications", "Baby Proofing"],

  // Special Services
  "Chimney Cleaning": ["Fireplace Maintenance", "Roof Maintenance"],
  "Foundation Repair": ["Basement Waterproofing", "Structural Maintenance", "Masonry Repair"],
  "Insulation Installation": ["Weatherstripping", "Energy Audit", "Soundproofing", "Attic Cleaning"],
  "Home Office Setup": ["Computer Setup & Troubleshooting", "Home Network Setup", "Organization"],
  "Home Gym Setup": ["Home Improvement", "Acoustic Panel Installation", "Organization"],
  "Baby Proofing": ["Nursery Setup", "Grab Bar Installation", "Lock Installation or Repair"],
  "General Handyman": ["Minor Home Repairs", "Home Maintenance", "Light Carpentry"],
}

export function getSuggestedServices(selectedServices: string[]): string[] {
  const suggestions = new Set<string>()

  selectedServices.forEach((service) => {
    const related = SERVICE_RELATIONSHIPS[service] || []
    related.forEach((relatedService) => {
      if (!selectedServices.includes(relatedService)) {
        suggestions.add(relatedService)
      }
    })
  })

  return Array.from(suggestions).slice(0, 5) // Limit to 5 suggestions
}
