export const SERVICES = [
  "Accessibility Modifications",
  "Acoustic Panel Installation",
  "Air Duct Cleaning",
  "Air Purifier Installation",
  "Appliance Repair",
  "Aquarium Maintenance",
  "Asbestos Removal",
  "Asphalt Shingle Preservation",
  "Asphalt Shingle Rejuvenation",
  "Asphalt Shingles Maintenance",
  "Asphalt Shingles Replacement",
  "Attic Cleaning",
  "Baby Proofing",
  "Basement Waterproofing",
  "Bathtub Refinishing",
  "Bed Assembly",
  "Blinds Repair",
  "Builders",
  "Cabinet Installation",
  "Carbon Monoxide Detector Maintenance",
  "Car Washing",
  "Carpet Cleaning",
  "Carpentry Services",
  "Cedar Shake Maintenance",
  "Cedar Shake Replacement",
  "Ceiling Repair",
  "Child Safety Gate Installation",
  "Chimney Cleaning",
  "Cleaning",
  "Composting System Setup",
  "Countertop Installation",
  "Curtain Rod Installation",
  "Deck Construction",
  "Decoration",
  "Deep Cleaning",
  "Dog Walking",
  "Driveway Sealing",
  "Dry Cleaning",
  "Drywall Repair",
  "Electrical Assistance",
  "Elevator Maintenance",
  "Energy Audit",
  "EV Charger Installation",
  "Fence Painting",
  "Fencing",
  "Fireplace Maintenance",
  "Fireproofing",
  "Floor Installation",
  "Floor Refinishing",
  "Foundation Repair",
  "Furniture Assembly",
  "Garage Door Repair",
  "Garden Bed Installation",
  "Gardening",
  "Gate Installation & Repair",
  "General Handyman",
  "Glass Repair",
  "Green Roof Installation",
  "Grout Repair",
  "Gutter Installation & Cleaning",
  "Gutter Repair",
  "Hang Art",
  "Hang Curtains",
  "Heavy Lifting & Loading",
  "Help Moving",
  "Holiday Decoration Removal",
  "Holiday Decoration Setup",
  "Home Automation Services",
  "Home Gym Setup",
  "Home Improvement",
  "Home Maintenance",
  "Home Network Setup",
  "Home Office Setup",
  "Home Staging",
  "Home Theater Setup",
  "House Cleaning",
  "HVAC Maintenance",
  "Humidifier Installation",
  "IKEA Assembly",
  "Indoor Painting",
  "Insulating Installation",
  "Install Blinds",
  "Install Window Treatments",
  "Insulation Installation",
  "Interior Decoration",
  "Landscaping",
  "Laundry and Ironing",
  "Lawncare",
  "Light Carpentry",
  "Light Installation",
  "Linens Washing",
  "Lock Installation or Repair",
  "Masonry Repair",
  "Minor Home Repairs",
  "Mirror Installation",
  "Mold Remediation",
  "Move-In/Move-Out Cleaning",
  "Nursery Setup",
  "Odor Removal",
  "Organization",
  "Outdoor Kitchen Installation",
  "Outdoor Lighting Installation",
  "Outdoor Maintenance",
  "Oven Cleaning",
  "Packing & Unpacking",
  "Painting & Decorating",
  "Party Cleanup",
  "Party Setup",
  "Patio Installation",
  "Pergola Construction",
  "Pet Cleanup",
  "Pet Door Installation",
  "Pet Grooming",
  "Pet Kennel Cleaning",
  "Pet Sitting",
  "Pet Training",
  "Pet Waste Removal",
  "Picture Hanging",
  "Playground Installation",
  "Plumbing",
  "Pond Maintenance",
  "Pool Maintenance",
  "Pool Table Maintenance",
  "Post-Construction Cleaning",
  "Pressure Washing",
  "Rainwater Harvesting System Installation",
  "Refrigerator Cleaning",
  "Retaining Wall Construction",
  "Rodent Control",
  "Roof Maintenance",
  "Roof Repair & Replacement",
  "Room Measurement",
  "Safe Installation",
  "Satellite & Set Top Boxes Installation",
  "Sauna Maintenance",
  "Security System Installation",
  "Septic Tank Maintenance",
  "Sewing",
  "Shed Installation",
  "Shelf Installation",
  "Siding Repair",
  "Skylight Installation",
  "Smart Home Installation",
  "Smart Lighting Setup",
  "Smart Lock Installation",
  "Smoke Detector Maintenance",
  "Snow Removal",
  "Solar Panel Installation",
  "Solar Panel Maintenance",
  "Soundproofing",
  "Spring Cleaning",
  "Sprinkler System Installation",
  "Sprinkler System Maintenance",
  "Storm Damage Repair",
  "Structural Maintenance",
  "Stump Grinding",
  "Sump Pump Maintenance",
  "Thermostat Installation & Repair",
  "Tile Installation",
  "Tile and Grout Cleaning",
  "Toy Organization",
  "Trash & Furniture Removal",
  "Tree Removal",
  "TV & Home Theater Installation",
  "TV Mounting",
  "Upholstery Cleaning",
  "Vintage Home Restoration",
  "Wallpapering",
  "Wallpaper Removal",
  "Water Heater Maintenance",
  "Weatherstripping",
  "Wildlife Removal",
  "Window Cleaning",
  "Window Sealing",
  "Windows & Doors Repair",
  "Wine Cellar Maintenance",
  "Yard Work",
].sort()

// Services that require structure details (house size, stories, property type)
export const SERVICES_REQUIRING_STRUCTURE_DETAILS = [
  "Accessibility Modifications",
  "Asphalt Shingles Maintenance",
  "Asphalt Shingles Replacement",
  "Basement Waterproofing",
  "Builders",
  "Cabinet Installation",
  "Carpentry Services",
  "Cedar Shake Maintenance",
  "Cedar Shake Replacement",
  "Ceiling Repair",
  "Countertop Installation",
  "Deck Construction",
  "Drywall Repair",
  "Electrical Assistance",
  "Floor Installation",
  "Floor Refinishing",
  "Foundation Repair",
  "General Handyman",
  "Green Roof Installation",
  "Gutter Installation & Cleaning",
  "Gutter Repair",
  "Home Improvement",
  "Home Maintenance",
  "HVAC Maintenance",
  "Indoor Painting",
  "Insulating Installation",
  "Insulation Installation",
  "Light Carpentry",
  "Masonry Repair",
  "Minor Home Repairs",
  "Painting & Decorating",
  "Patio Installation",
  "Pergola Construction",
  "Plumbing",
  "Roof Maintenance",
  "Roof Repair & Replacement",
  "Siding Repair",
  "Skylight Installation",
  "Solar Panel Installation",
  "Structural Maintenance",
  "Wallpapering",
  "Window Sealing",
]
